---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Home dashboard"
subtitle: "Internet of Everything"
icon: "fas fa-home"

header: true
footer: '<p>Created by Niels with Homer</p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank" # optional html a tag target attribute
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Applications"
    icon: "fas fa-file"
    items:
      - name: "Home Assistant"
        logo: "assets/tools/HomeAssistantLogo.png"
        subtitle: "Smart Home"
        url: "https://home-assistant.url.com"
      - name: "Node-RED"
        logo: "assets/tools/nodered.png"
        subtitle: "Connecting nodes"
        url: "https://node-red.url.com"      
      - name: "Grafana"
        logo: "assets/tools/grafana.png"
        subtitle: "IoT Dashboard"
        url: "https://grafana.url.com"
  - name: "Network"
    icon: "fas fa-code-branch"
    items:
      - name: "Portainer"
        logo: "assets/tools/PortainerLogo.png"
        subtitle: "Docker management GUI"
        url: "https://portainer.url.com 
      - name: "Pi-Hole"
        logo: "assets/tools/pihole.png"
        subtitle: "Adblocker DNS-sinkhole"
        url: "https://pi-hole.com/admin"
      - name: "Cloudflare"
        logo: "assets/tools/cloudflare.png"
        subtitle: "Network Access Tunnel"
        url: "https://one.dash.cloudflare.com"
